export const A = {
  LOAD_START:       'LOAD_START',
  LOAD_SUCCESS:     'LOAD_SUCCESS',
  LOAD_ERROR:       'LOAD_ERROR',
  SET_TOKEN:        'SET_TOKEN',
  SET_COMPLETIONS:  'SET_COMPLETIONS',
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  APPEND_APP_LOG:   'APPEND_APP_LOG',
  SET_MOW_LOG:      'SET_MOW_LOG',
  SET_WATER_LOG:    'SET_WATER_LOG',
  UPSERT_WEATHER:   'UPSERT_WEATHER',
  DELETE_WEATHER:   'DELETE_WEATHER',
  BUILD_INV_CACHE:  'BUILD_INV_CACHE',
  SET_UI:           'SET_UI',
} as const

export type ActionType = typeof A[keyof typeof A]
